### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by seanaguinaga** [arin2115/icloudapi#1]
Hey there

I want to contribute and add the rest of the Todo items

I am not sure how you found out about all of their endpoints and such, just curious if you could explain some of it to me and where you think I could start to get those other parts working?

**Comment by arin2115** [comment]
Hey, very nice that you want to contribute to my project.

Basically every endpoint you can find out from response of login request. [Line of code](https://github.com/arin2115/icloudapi/blob/0352a592489f655426f9d69c7be9d6e2b9893b3b/index.js#L328)

Documentation of them isn't available obviously, but it's possible to reverse enginner.
By using some proxies (e.g. [Charles](https://www.charlesproxy.com/)) and opening an app (e.g Calendar) you can grab requests of it.

There are also other repositiories that have many other endpoints included, but most of them are outdated and some endpoints may be already changed.

**Comment by arin2115** [comment]
There is an app called Proxyman for iOS, and it makes it's job very well.

Was able to successfully and easily get request to FMF (FindMy Friends) api, which I guess is not anywhere available on github.

Probably today (16.07) I'll update the library with this FMF endpoint.

**Comment by arin2115** [comment]
As of no response, I'm closing this issue for now.
